import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";

import { ReactNode } from "react";
import ActiveStutas from "@/components/conversations/ActiveStutas";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
