export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { AppSidebar } from "@/components/app-sidebar";
import "../globals.css";
import Providers from "../Providers";
import React from "react";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import ConversationsList from "@/components/conversations/ConversationsList";
import { getAllUsers, getConversations } from "@/utils/action";
import HadChatFrind from "@/components/chat/HadChatFrind";
import SearshChat from "@/components/chat/SearshChat";
import ActiveStutas from "@/components/conversations/ActiveStutas";
export default async function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  const Conversations = await getConversations();
  if (!session?.user) redirect("/login");
  const users = await getAllUsers();
  return (
    <SidebarProvider>
      <ActiveStutas />
      <AppSidebar session={session} />
      <SidebarInset className="bg-[#0b141a] text-[#d1d7db]">
        <header className="flex h-20 items-center border-b border-white/10 bg-gradient-to-r from-[#00a884] to-[#075e54] text-white shadow-lg transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-16">
          <div className="flex w-full items-center justify-between px-4">
            <div>
              <p className="text-lg font-semibold tracking-wide">WhatsApp</p>
              <p className="text-xs text-white/80">End-to-end encrypted chats</p>
            </div>
            <SidebarTrigger className="rounded-full bg-white/10 p-2 text-white transition hover:bg-white/20" />
          </div>
        </header>
        <div className="flex w-full flex-1 gap-4 px-4 pb-4 pt-4">
          <div className="flex w-full max-w-md flex-col gap-3 rounded-[28px] border border-white/5 bg-[#111b21] shadow-2xl shadow-black/40">
            <HadChatFrind users={users} />
            <SearshChat />
            <ConversationsList intialItems={Conversations} />
          </div>
          <Providers>
            <div className="flex h-full w-full flex-1">
              {children}
            </div>
          </Providers>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
