export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { AppSidebar } from "@/components/app-sidebar";
import "../globals.css";
import Providers from "../Providers";
import React from "react";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import ConversationsList from "@/components/conversations/ConversationsList";
import { getAllUsers, getConversations } from "@/utils/action";
import HadChatFrind from "@/components/chat/HadChatFrind";
import SearshChat from "@/components/chat/SearshChat";
export default async function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  const Conversations = await getConversations();
  if (!session?.user) redirect("/login");
  const users = await getAllUsers();
  return (
    <SidebarProvider>
      <AppSidebar session={session} />
      <SidebarInset>
        <header className="flex  h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
          </div>
        </header>
        <div className="flex w-full  flex-1  pl-4 pt-0">
          <div className="rounded-xl  bg-neutral-200 dark:bg-neutral-900 rounded-tr-none rounded-br-none overflow-hidden h-full  w-full">
            <HadChatFrind users={users} />
            <SearshChat />
            <ConversationsList intialItems={Conversations} />
          </div>
        </div>
      </SidebarInset>
      <Providers>{children}</Providers>
    </SidebarProvider>
  );
}
