export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "../globals.css";
import Providers from "../Providers";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Providers>{children}</Providers>;
}
